<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Stef Heyenrath</Authors>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SimMetrics.Net.Tests</AssemblyName>
    <PackageId>SimMetrics.Net.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SimMetrics.Net\SimMetrics.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--<Reference Include="System" />-->
    <!--<Reference Include="Microsoft.CSharp" />-->
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NFluent" Version="3.1.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>